#!/bin/bash
# 99-fix-xorg.sh
# Xorg config has been generated by 70-configure_xorg.sh using nvidia-xconfig.
# We just need to ensure Sunshine captures X11.
mkdir -p /templates/sunshine
echo "capture = x11" >> /templates/sunshine/sunshine.conf
mkdir -p /home/default/.config/sunshine
grep -qxF 'capture = x11' /home/default/.config/sunshine/sunshine.conf 2>/dev/null || echo "capture = x11" >> /home/default/.config/sunshine/sunshine.conf
chown -R default:default /home/default/.config/sunshine 2>/dev/null || true
